apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428/select/0/prometheus
    isDefault: true
    editable: true

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: victoriametrics
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-10m"
        spanEndTimeShift: "10m"
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: victoriametrics
